server:
  port: 7001
  
eureka:
  server:
    enable-self-preservation: true #(关闭false/开启true，默认开启)eureka自我保护机制
    #renewal-percent-threshold: 0.49  #(定义了renews 和renews threshold的比值，默认值为0.85,当server在15分钟内，比值低于percent，即少了15%的微服务心跳，server会进入自我保护状态，Self-Preservation。在此状态下，server不会删除注册信息，这就有可能导致在调用微服务时，实际上服务并不存在。)
  instance:
    hostname: www.eureka.7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry:  false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
       #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
       #http://www.eureka.7002.com:7002/eureka,http://www.eureka.7003.com:7003/eureka
      defaultZone: http://www.eureka.7002.com:7002/eureka,http://www.eureka.7003.com:7003/eureka
         